version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo "https://github.com/kptdobe/helix-sections-playground.git#master"

  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo

strains:
  - name: default
    <<: *basestrain
    package: acapt/8315775bd06765fb594a48e8d23162c77f399ed0
